AWSTemplateFormatVersion: '2010-09-09'
Description: 'tweet-sentiment

  Performs Tweet Sentiment Analysis, logs sentiment scores to CW Metrics

  '
Outputs:
  TweetSentimentFunction:
    Description: TweetSentiment Lambda Function ARN
    Value:
      Fn::GetAtt:
      - TweetSentiment
      - Arn
Resources:
  TweetSentiment:
    Properties:
      CodeUri: s3://abhishektweet/6c900e8a2b31fd9aac565766b6a8ea2e
      Handler: com.abhishektweet.serverless.tweetsentiment.lambda.TweetSentimentHandler::handleRequest
      MemorySize: 768
      Policies:
      - ComprehendBasicAccessPolicy: {}
      - CloudWatchPutMetricPolicy: {}
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
